export const auth: Record<string, string> = {
  "Faltan campos": "Missing fields",
  "Email inválido": "Invalid email",
  "La contraseña debe tener entre 8 y 128 caracteres": "Password must be 8 to 128 characters",
  "Email ya registrado": "This email is already registered",
  "Enlace inválido": "Invalid link",
  "Enlace inválido o ya usado": "Invalid or already used link",
  "El enlace venció. Solicita uno nuevo.": "This link has expired. Request a new one.",
  "Escribe tu correo": "Enter your email",
  "No hay ninguna cuenta registrada con ese correo.": "There is no account registered with that email.",
  "No pudimos enviar el correo. Intenta de nuevo en unos minutos.": "We couldn't send the email. Try again in a few minutes.",
  "La contraseña no es correcta": "Incorrect password",
  "Eres el único admin: nombra a otro admin antes de eliminar tu cuenta.": "You're the only admin: appoint another admin before deleting your account.",
  "Primero cancela tus reservas activas y pausa tus posadas.": "First cancel your active bookings and pause your posadas.",
  "Email o contraseña incorrectos": "Incorrect email or password",
  "Iniciando sesión…": "Signing in…",
  "Iniciar sesión": "Sign in",
  "Volver al inicio": "Back to home",
  "Bienvenido de vuelta": "Welcome back",
  "Inicia sesión para gestionar tus reservas": "Sign in to manage your bookings",
  "Contraseña": "Password",
  "¿Olvidaste tu contraseña?": "Forgot your password?",
  "Regístrate gratis": "Sign up for free",
  "¿No tienes cuenta?": "Don't have an account?",
  "tu@email.com": "you@email.com",
  "Error al registrar": "Sign-up failed",
  "Cuenta creada, pero error al iniciar sesión automáticamente": "Account created, but we couldn't sign you in automatically",
  "Creando cuenta…": "Creating account…",
  "Crear cuenta gratis": "Create free account",
  "Crea tu cuenta": "Create your account",
  "Únete a la comunidad de posadas venezolanas": "Join Venezuela's posada community",
  "Soy…": "I'm a…",
  "Viajero": "Traveler",
  "Quiero explorar y reservar posadas": "I want to explore and book posadas",
  "Posadero": "Host",
  "Quiero publicar mi posada": "I want to list my posada",
  "Nombre completo": "Full name",
  "Términos": "Terms",
  "Política de privacidad": "Privacy policy",
  "condiciones para posaderos": "host conditions",
  "Inicia sesión": "Sign in",
  "Tu nombre": "Your name",
  "Mínimo 8 caracteres": "At least 8 characters",
  "Al crear tu cuenta aceptas los": "By creating an account you accept the",
  "y la": "and the",
  "y las": "and the",
  "10% por reserva confirmada, mismo precio y mismas ofertas que en otros canales, y comunicación dentro de la app": "10% per confirmed booking, same prices and offers as on other channels, and communication inside the app",
  "¿Ya tienes cuenta?": "Already have an account?",
  "No pudimos procesar la solicitud.": "We couldn't process the request.",
  "Error de conexión. Intenta de nuevo.": "Connection error. Please try again.",
  "Enviando…": "Sending…",
  "Enviar enlace": "Send link",
  "Revisa tu correo": "Check your email",
  "Revisa tu bandeja de entrada (y la carpeta de spam).": "Check your inbox (and your spam folder).",
  "← Volver a iniciar sesión": "← Back to sign in",
  "Ingresa tu correo y te enviaremos un enlace para restablecerla.": "Enter your email and we'll send you a link to reset it.",
  "Correo electrónico": "Email",
  "Crear una cuenta →": "Create an account →",
  "Te enviamos a": "We sent",
  "un enlace para crear una nueva contraseña. El enlace vence en 1 hora.": "a link to create a new password. The link expires in 1 hour.",
  "No se pudo restablecer": "Couldn't reset the password",
  "La contraseña debe tener al menos 8 caracteres": "Password must be at least 8 characters",
  "Las contraseñas no coinciden": "Passwords don't match",
  "Error de red. Intenta de nuevo.": "Network error. Please try again.",
  "Guardando…": "Saving…",
  "Guardar contraseña": "Save password",
  "Este enlace no es válido. Solicita uno nuevo.": "This link is not valid. Request a new one.",
  "← Solicitar enlace de recuperación": "← Request a recovery link",
  "¡Contraseña actualizada!": "Password updated!",
  "Listo. Ya puedes iniciar sesión con tu nueva contraseña. Redirigiendo…": "Done. You can now sign in with your new password. Redirecting…",
  "Ir a iniciar sesión →": "Go to sign in →",
  "Nueva contraseña": "New password",
  "Crea una contraseña nueva para tu cuenta.": "Create a new password for your account.",
  "Repite la contraseña": "Repeat the password",
}
