export const buscar: Record<string, string> = {
  "Cargando mapa…": "Loading map…",
  "{n} noches": "{n} nights",
  "{n} noche": "{n} night",
  "Selecciona la entrada": "Select check-in",
  "Ahora elige la salida": "Now choose check-out",
  "{n} semana": "{n} week",
  "{n} semanas": "{n} weeks",
  "Borrar fechas": "Clear dates",
  "Meses": "Months",
  "Semanas": "Weeks",
  "¿En qué mes quieres viajar?": "Which month do you want to travel?",
  "Borrar selección": "Clear selection",
  "¿Cuánto tiempo quieres quedarte?": "How long do you want to stay?",
  "Cualquier semana": "Any week",
  "Selecciona tus fechas": "Select your dates",
  "Método de pago": "Payment method",
  "Total estimado": "Estimated total",
  "Destinos": "Destinations",
  "Posaderos": "For hosts",
  "Cómo funciona": "How it works",
  "Destino": "Destination",
  "Sugerencias de destinos": "Suggested destinations",
  "Buscar en toda Venezuela": "Search all of Venezuela",
  "Ver todas las posadas disponibles": "See all available posadas",
  "Popular": "Popular",
  "Regiones": "Regions",
  "Región": "Region",
  "Fechas": "Dates",
  "Fechas exactas": "Exact dates",
  "Fechas flexibles": "Flexible dates",
  "Pago": "Payment",
  "Precio máximo / noche": "Max price / night",
  "Ordenar:": "Sort by:",
  "Sin resultados": "No results",
  "Prueba con otro destino o ajusta los filtros": "Try another destination or adjust the filters",
  "Ver detalles →": "View details →",
  "Ver todos los detalles →": "See all details →",
  "Buscar": "Search",
  "Lista": "List",
  "Mapa": "Map",
  "Cerrar": "Close",
  "Borrar": "Clear",
  "¿A dónde vas?": "Where are you going?",
  "Volver a la lista": "Back to list",
  "Foto {n}": "Photo {n}",
  "{n} hab.": "{n} rooms",
  "/noche": "/night",
  "ENTRADA": "CHECK-IN",
  "SALIDA": "CHECK-OUT",
  "Agregar fecha": "Add date",
  "Selecciona un método": "Choose a method",
  "Reservar · ${total} USD": "Book · ${total} USD",
  "Reservar ahora": "Book now",
  "Anfitrión: {name}": "Host: {name}",
  "Posadero desde {y}": "Host since {y}",
  "Salida": "Check-out",
  "Buscando en Venezuela…": "Searching Venezuela…",
  "Sin resultados para «{q}»": "No results for “{q}”",
  "Cualquier opción": "Any option",
  "posadas encontradas": "posadas found",
  "posada encontrada": "posada found",
  "cerca de {place}": "near {place}",
  "Valoración": "Rating",
  "Precio": "Price",
  "Distancia": "Distance",
  "No hay posadas exactas en «{q}»": "No exact matches for “{q}”",
  "Mostrando las más cercanas a {place}": "Showing the closest ones to {place}",
  "Mostrando las más cercanas": "Showing the closest ones",
  "zona cercana": "nearby area",
  "Cargando…": "Loading…",
}
