// Vocabulario fijo que eligen los posaderos al publicar (tipos, etiquetas, servicios,
// formas de pago) y nombres de regiones. El texto libre de cada posada no se traduce.
export const catalog: Record<string, string> = {
  // Valoración
  'Nueva': 'New',
  'Nueva en RESER-VE': 'New on RESER-VE',
  '{n} reseña': '{n} review',
  '{n} reseñas': '{n} reviews',
  // Tipos
  'Posada': 'Posada',
  'Posada de playa': 'Beach posada',
  'Posada de montaña': 'Mountain posada',
  'Posada rural': 'Countryside posada',
  'Posada urbana': 'City posada',
  'Posada de aventura': 'Adventure posada',
  'Eco-posada': 'Eco-posada',
  'Hostal': 'Hostel',
  'Cabaña': 'Cabin',
  'Campamento': 'Camp',
  'Apartamento': 'Apartment',
  // Etiquetas
  'Frente al mar': 'Beachfront',
  'Vista a la montaña': 'Mountain view',
  'Desayuno incluido': 'Breakfast included',
  'Pet friendly': 'Pet friendly',
  'Piscina': 'Pool',
  'Wi-Fi': 'Wi-Fi',
  'Aire acondicionado': 'Air conditioning',
  'Estacionamiento': 'Parking',
  'Chimenea': 'Fireplace',
  'Acceso privado a playa': 'Private beach access',
  'Rodeado de naturaleza': 'Surrounded by nature',
  'Vistas panorámicas': 'Panoramic views',
  // Servicios
  'Bar': 'Bar',
  'Agua caliente': 'Hot water',
  'Cocina equipada': 'Equipped kitchen',
  'Lavandería': 'Laundry',
  'Traslados': 'Transfers',
  'Tours guiados': 'Guided tours',
  'Snorkel / Buceo': 'Snorkeling / Diving',
  'Kayak': 'Kayak',
  'Hamacas': 'Hammocks',
  'Cocina criolla': 'Venezuelan home cooking',
  // Formas de pago
  'Zelle': 'Zelle',
  'Pago Móvil': 'Pago Móvil',
  'Transferencia': 'Bank transfer',
  'Transferencia bancaria': 'Bank transfer',
  'Efectivo USD': 'Cash (USD)',
  'Efectivo Bs': 'Cash (Bs)',
  'Binance / USDT': 'Binance / USDT',
  'Zinli': 'Zinli',
  'Tarjeta': 'Card',
  'Tarjeta de crédito': 'Credit card',
  // Idiomas del anfitrión
  'Español': 'Spanish',
  'Inglés': 'English',
  'Portugués': 'Portuguese',
  'Francés': 'French',
  'Italiano': 'Italian',
  'Alemán': 'German',
  'Pemón': 'Pemón',
  // Regiones y estados
  'Caribe Occidental': 'Western Caribbean',
  'Caribe Central': 'Central Caribbean',
  'Caribe Oriental': 'Eastern Caribbean',
  'Islas del Caribe': 'Caribbean Islands',
  'Los Andes': 'The Andes',
  'Andes': 'Andes',
  'Los Llanos': 'Los Llanos (plains)',
  'Gran Sabana y Canaima': 'Gran Sabana & Canaima',
  'Amazonas': 'Amazonas',
  'Delta del Orinoco': 'Orinoco Delta',
  'Región Central': 'Central Region',
  'Capital': 'Capital District',
  'Dependencias Federales': 'Federal Dependencies',
}
