export const chat: Record<string, string> = {
  "Abrir ayuda de Chigüi": "Open Chigüi's help",
  "Chigüi · Ayuda RESER-VE": "Chigüi · RESER-VE Help",
  "En línea · el chigüire de RESER-VE": "Online · RESER-VE's capybara",
  "El equipo te respondió en «{s}» · Ver →": "The team replied in “{s}” · View →",
  "¿Cuándo abren las reservas?": "When do bookings open?",
  "¿Qué métodos de pago aceptan?": "Which payment methods do you accept?",
  "¿Cómo publico mi posada?": "How do I list my posada?",
  "Quiero hablar con un agente": "I want to talk to a person",
  "Ticket abierto. Te avisamos por correo y aquí mismo cuando el equipo responda.": "Ticket opened. We'll let you know by email and right here when the team replies.",
  "Ver ticket →": "View ticket →",
  "Equipo RESER-VE": "RESER-VE team",
  "Ups, tuve un problema para responder. Intenta de nuevo o escríbenos a hola@reser-ve.com.": "Oops, I had trouble replying. Try again or email us at hola@reser-ve.com.",
  "Escribe al equipo de RESER-VE…": "Write to the RESER-VE team…",
  "Escribe tu mensaje…": "Write your message…",
  "IA de RESER-VE · puede cometer errores": "RESER-VE AI · can make mistakes",
  "¡Hola! Soy Chigüi, el chigüire de RESER-VE. Puedo contarte sobre las posadas, cómo funcionarán las reservas y los pagos, ayudarte a publicar tu posada o conectarte con una persona del equipo. ¿En qué te ayudo?": "Hi! I'm Chigüi, RESER-VE's capybara. I can tell you about the posadas and how bookings and payments will work, help you list your posada, or connect you with someone from the team. How can I help?",
  "5 días entre playa y aventura en agosto, presupuesto $500": "5 days of beach and adventure in August, $500 budget",
  "Luna de miel romántica frente al mar, 4 noches": "Romantic beachfront honeymoon, 4 nights",
  "Escapada familiar a la montaña con 2 niños": "Family mountain getaway with 2 kids",
  "Quiero ver el Salto Ángel y los tepuyes, 6 días": "I want to see Angel Falls and the tepuis, 6 days",
  "Aurora, la guacamaya viajera": "Aurora, the traveling macaw",
  "La guacamaya viajera de RESER-VE": "RESER-VE's traveling macaw",
  "¡Epa! Soy": "Hey there! I'm",
  "He volado de Los Roques a los tepuyes y de los Andes a Margarita. Cuéntame qué viaje sueñas y te armo la ruta con posadas reales, fechas y precios. ¿Pa' dónde vamos?": "I've flown from Los Roques to the tepuis and from the Andes to Margarita. Tell me about the trip you dream of and I'll put together a route with real posadas, dates and prices. Where are we headed?",
  "/noche": "/night",
  "Ver posada →": "View posada →",
  "Buscando posadas…": "Searching posadas…",
  "Verificando disponibilidad…": "Checking availability…",
  "Tuve un problema para responder. Intenta de nuevo en un momento. 🙏": "I had trouble replying. Please try again in a moment. 🙏",
  "Ej: 4 noches en Los Roques y Canaima, 2 personas, presupuesto $600…": "e.g. 4 nights in Los Roques and Canaima, 2 people, $600 budget…",
  "Enviar": "Send",
  "Aurora usa IA y datos reales de RESER-VE · puede cometer errores": "Aurora uses AI and real RESER-VE data · can make mistakes",
}
