export const ficha: Record<string, string> = {
  "Cargando…": "Loading…",
  "Posada no encontrada": "Posada not found",
  "← Volver a búsqueda": "← Back to search",
  "Inicio": "Home",
  "Posadas": "Posadas",
  "Sobre esta posada": "About this posada",
  "Servicios incluidos": "Amenities",
  "Tu anfitrión": "Your host",
  "Superposadero": "Superhost",
  "Políticas de la posada": "House policies",
  "Llegada": "Check-in",
  "Salida": "Check-out",
  "Huéspedes": "Guests",
  "Total": "Total",
  "Reserva protegida · Sin cobro automático": "Protected booking · No automatic charge",
  "Chatea con el posadero dentro de RESER-VE. Por tu seguridad, mantén la comunicación y el pago en la plataforma.": "Chat with the host inside RESER-VE. For your safety, keep communication and payment on the platform.",
  "Sin cargos hasta confirmar. El posadero acepta en 24h.": "No charges until confirmed. The host replies within 24h.",
  "{n} habitación": "{n} room",
  "{n} habitaciones": "{n} rooms",
  "Posadero": "Host",
  "Posadero desde {y}": "Host since {y}",
  "Idiomas: {list}": "Languages: {list}",
  "Reseñas · ★ {r} · {n} opiniones": "Reviews · ★ {r} · {n} reviews",
  "USD / noche": "USD / night",
  "{n} huésped": "{n} guest",
  "{n} huéspedes": "{n} guests",
  "Reservar · {n} noches": "Book · {n} nights",
  "Reservar · {n} noche": "Book · {n} night",
  "Reservar ahora": "Book now",
  "Abriendo chat…": "Opening chat…",
  "Escribir al posadero": "Message the host",
  "{n} noches": "{n} nights",
  "{n} noche": "{n} night",
}
