// Portada y buscador de la portada.
export const home: Record<string, string> = {
  "{n} posadas": "{n} posadas",
  "{n} posada": "{n} posada",
  "{n} semanas": "{n} weeks",
  "{n} semana": "{n} week",
  "Fechas flexibles": "Flexible dates",
  "Salida": "Check-out",
  "Fechas": "Dates",
  "Archipiélago": "Archipelago",
  "Los Andes": "The Andes",
  "Costa Oriental": "Eastern coast",
  "Costa Occidental": "Western coast",
  "Gran Sabana": "Gran Sabana",
  "Caribe": "Caribbean",
  "Todos los destinos": "All destinations",
  "Gran Sabana, Coro, Choroní y más": "Gran Sabana, Coro, Choroní and more",
  "Destinos": "Destinations",
  "Posaderos": "For hosts",
  "Cómo funciona": "How it works",
  "Menú": "Menu",
  "Cerrar": "Close",
  "Sueña tu viaje con Aurora": "Dream your trip with Aurora",
  "Sobre nosotros": "About us",
  "Preguntas frecuentes": "Frequently asked questions",
  "Encuentra tu": "Find your",
  "posada": "posada",
  "en Venezuela": "in Venezuela",
  "Posadas familiares de Los Roques a la Gran Sabana. Compara fotos, precios y formas de pago, y paga exactamente el precio publicado.": "Family-run guesthouses from Los Roques to the Gran Sabana. Compare photos, prices and payment options, and pay exactly the listed price.",
  "Ver posadas": "Browse posadas",
  "Publica tu posada": "List your posada",
  "Foto {n}": "Photo {n}",
  "Destino": "Destination",
  "¿A dónde vas?": "Where are you going?",
  "Sugerencias de destinos": "Suggested destinations",
  "Buscar en toda Venezuela": "Search all of Venezuela",
  "Ver todas las posadas disponibles": "See all available posadas",
  "Popular": "Popular",
  "Regiones": "Regions",
  "Región": "Region",
  "Buscando en Venezuela…": "Searching Venezuela…",
  "Sin resultados para «{q}»": "No results for “{q}”",
  "Fechas exactas": "Exact dates",
  "{n} noches": "{n} nights",
  "{n} noche": "{n} night",
  "Selecciona entrada": "Select check-in",
  "Selecciona salida": "Select check-out",
  "Borrar": "Clear",
  "Meses": "Months",
  "Semanas": "Weeks",
  "¿En qué mes quieres viajar?": "Which month do you want to travel?",
  "Borrar selección": "Clear selection",
  "¿Cuánto tiempo quieres quedarte?": "How long do you want to stay?",
  "Cualquier semana": "Any week",
  "Pago": "Payment",
  "Cualquier opción": "Any option",
  "Transferencia bancaria": "Bank transfer",
  "Efectivo USD": "Cash (USD)",
  "Efectivo Bs": "Cash (Bs)",
  "Tarjeta de crédito": "Credit card",
  "Transferencia": "Bank transfer",
  "Tarjeta": "Card",
  "Zelle": "Zelle",
  "Pago Móvil": "Pago Móvil",
  "Buscar": "Search",
  "Habitación de una posada en Canaima": "Room at a posada in Canaima",
  "Alojamiento": "Stay",
  "Posadas familiares": "Family-run posadas",
  "Posada en Canaima": "Posada in Canaima",
  "Sobre las posadas": "About posadas",
  "¿Qué es una posada?": "What is a posada?",
  "Un alojamiento pequeño, casi siempre familiar. Los dueños viven en el lugar o cerca, conocen bien la zona y atienden en persona. Suelen tener pocas habitaciones, desayuno casero y precios más accesibles que un hotel.": "A small, usually family-run guesthouse. The owners live on site or nearby, know the area well and look after you personally. They tend to have just a few rooms, homemade breakfast and lower prices than a hotel.",
  "Bien ubicadas": "Great locations",
  "Frente al mar, en la montaña o junto a los parques nacionales": "By the sea, in the mountains or next to national parks",
  "Atención de los dueños": "Run by the owners",
  "Te recomiendan tours, traslados y dónde comer": "They recommend tours, transfers and where to eat",
  "Pago en USD o Bs": "Pay in USD or Bs",
  "Zelle, Pago Móvil, transferencia o efectivo, según la posada": "Zelle, Pago Móvil, bank transfer or cash, depending on the posada",
  "Revisadas": "Reviewed",
  "Cada posada pasa por nuestro equipo antes de publicarse": "Every posada is checked by our team before going live",
  "Así funciona RESER-VE": "How RESER-VE works",
  "Estamos en fase privada: las posadas ya se están publicando y las reservas abren pronto.": "We're in private beta: posadas are being listed now and bookings open soon.",
  "Soy viajero": "I'm a traveler",
  "Tengo una posada": "I have a posada",
  "Busca": "Search",
  "Filtra por destino, precio y forma de pago, o mira las posadas en el mapa.": "Filter by destination, price and payment method, or browse posadas on the map.",
  "Compara": "Compare",
  "Revisa fotos, servicios, políticas y ubicación de cada posada.": "Check each posada's photos, amenities, policies and location.",
  "Solicita": "Request",
  "El posadero confirma en menos de 24 horas y te envía sus datos de pago por el chat.": "The host confirms within 24 hours and sends you their payment details through the chat.",
  "Viaja": "Travel",
  "Pagas a la posada, te hospedas y al volver puedes dejar tu reseña.": "You pay the posada, enjoy your stay and leave a review when you get back.",
  "Crea tu cuenta": "Create your account",
  "Regístrate como posadero. Publicar es gratis y no hay mensualidad.": "Sign up as a host. Listing is free and there's no monthly fee.",
  "Sube fotos, precios, habitaciones y las formas de pago que aceptas.": "Add photos, prices, rooms and the payment methods you accept.",
  "La revisamos": "We review it",
  "Nuestro equipo la revisa en 24 a 72 horas y te avisa por correo.": "Our team reviews it within 24 to 72 hours and emails you.",
  "Recibe solicitudes": "Receive requests",
  "Confirmas cada reserva desde tu panel y hablas con el huésped por el chat.": "Confirm each booking from your dashboard and talk to guests through the chat.",
  "Explora por destino": "Explore by destination",
  "Venezuela": "Venezuela",
  "Para posaderos": "For hosts",
  "¿Tienes una posada?": "Do you run a posada?",
  "Publícala gratis y llega a viajeros de Venezuela y del exterior que buscan dónde quedarse. Solo pagas una comisión cuando recibes una reserva confirmada.": "List it for free and reach travelers from Venezuela and abroad looking for a place to stay. You only pay a commission when you get a confirmed booking.",
  "Sin mensualidad ni costo de alta": "No monthly fee or sign-up cost",
  "Tu propia página con fotos, servicios, políticas y ubicación": "Your own page with photos, amenities, policies and location",
  "Calendario por habitaciones sincronizado con Booking, Airbnb y Google Calendar": "Room-by-room calendar synced with Booking, Airbnb and Google Calendar",
  "Cobras como siempre: Zelle, Pago Móvil, transferencia o efectivo": "Get paid as usual: Zelle, Pago Móvil, bank transfer or cash",
  "Un proyecto de": "A project by",
  "Empezar toma unos 10 minutos": "Getting started takes about 10 minutes",
  "Crea tu cuenta de posadero": "Create your host account",
  "Completa los datos y sube tus fotos": "Fill in the details and upload your photos",
  "Envíala a revisión": "Submit it for review",
  "Publicar mi posada": "List my posada",
  "Descargar la guía para posaderos (PDF)": "Download the host guide (PDF, Spanish)",
  "Reserva posadas en Venezuela, directamente con sus dueños.": "Book posadas in Venezuela, directly with their owners.",
  "Explorar": "Explore",
  "Registra tu posada": "List your posada",
  "Guía para posaderos (PDF)": "Host guide (PDF, Spanish)",
  "Contacto": "Contact",
  "Centro de ayuda": "Help center",
  "Impulsado por": "Powered by",
  "Términos": "Terms",
  "Privacidad": "Privacy",
  "Caribe Occidental": "Western Caribbean",
  "Caribe Central": "Central Caribbean",
  "Caribe Oriental": "Eastern Caribbean",
  "Islas del Caribe": "Caribbean Islands",
  "Los Llanos": "The Llanos (plains)",
  "Gran Sabana y Canaima": "Gran Sabana & Canaima",
  "Amazonas": "Amazonas",
  "Delta del Orinoco": "Orinoco Delta",
  "Región Central": "Central Region",
  "Andes": "Andes",
  "Capital": "Capital District",
  "Dependencias Federales": "Federal Dependencies"
}
