export const info: Record<string, string> = {
  "Preguntas frecuentes": "Frequently asked questions",
  "Respuestas a las preguntas más comunes sobre RESER-VE, reservas, pagos y posadas venezolanas.": "Answers to the most common questions about RESER-VE, bookings, payments and Venezuelan posadas.",
  "Todo lo que necesitas saber antes de reservar tu próxima aventura venezolana.": "Everything you need to know before booking your next Venezuelan adventure.",
  "¿Tienes otra pregunta?": "Have another question?",
  "Escríbenos y te respondemos en menos de 24 horas.": "Write to us and we'll reply within 24 hours.",
  "Contáctanos": "Contact us",
  "Explorar posadas": "Explore posadas",
  "Sobre RESER-VE": "About RESER-VE",
  "¿Qué es RESER-VE?": "What is RESER-VE?",
  "Una plataforma para encontrar y reservar posadas en Venezuela: Los Roques, Mérida, Mochima, Canaima, Margarita y más destinos. Cada posada tiene su página con fotos, precio, servicios y ubicación, y la coordinación con el posadero se hace por un chat dentro de la plataforma.": "A platform to find and book posadas (guesthouses) in Venezuela: Los Roques, Mérida, Mochima, Canaima, Margarita and more. Every posada has its own page with photos, price, amenities and location, and you coordinate with the host through a chat inside the platform.",
  "¿El viajero paga alguna comisión?": "Do travelers pay a fee?",
  "No. RESER-VE no cobra nada al viajero. El precio que ves es el precio final que pagas al posadero. Sin sorpresas, sin cargos ocultos.": "No. RESER-VE doesn't charge travelers anything. The price you see is the final price you pay the host. No surprises, no hidden fees.",
  "¿Cómo está respaldada la plataforma?": "Who is behind the platform?",
  "Reservas y pagos": "Bookings and payments",
  "¿Cómo funciona el proceso de reserva?": "How does booking work?",
  "Durante la fase privada las reservas aún no están abiertas: puedes crear tu cuenta y guardar tus favoritas. Cuando abran: encuentra tu posada en el buscador, elige fechas, huéspedes y método de pago, y envía tu solicitud. El posadero la confirma desde su panel y te llega un correo. Toda la coordinación (llegada, pago, detalles) se hace por el chat de RESER-VE, que deja registro y te protege ante fraudes.": "During the private beta bookings aren't open yet: you can create an account and save your favorites. Once they open: find your posada, choose dates, guests and payment method, and send your request. The host confirms it from their dashboard and you get an email. All coordination (arrival, payment, details) happens in the RESER-VE chat, which keeps a record and protects you from fraud.",
  "¿Qué métodos de pago se aceptan?": "Which payment methods are accepted?",
  "Cada posada define sus métodos de pago. Los más comunes en Venezuela son: Zelle (USD), transferencia bancaria venezolana (bolívares), efectivo en USD, efectivo en bolívares, y en algunos casos tarjeta de crédito. Puedes filtrar por método de pago en el buscador.": "Each posada sets its own payment methods. The most common in Venezuela are Zelle (USD), Venezuelan bank transfer (bolívars), cash in USD, cash in bolívars and, in some cases, credit card. You can filter by payment method in the search.",
  "¿Puedo cancelar mi reserva?": "Can I cancel my booking?",
  "Las políticas de cancelación las define cada posadero de forma individual. Encontrarás los detalles en la página de cada posada. Te recomendamos leerlas antes de confirmar tu reserva y escribirle al anfitrión por el chat de RESER-VE ante cualquier cambio.": "Each host sets their own cancellation policy. You'll find the details on each posada's page. We recommend reading them before confirming and messaging the host through the RESER-VE chat about any change.",
  "¿Es seguro pagar por Zelle?": "Is it safe to pay with Zelle?",
  "Zelle es el método de pago más utilizado entre venezolanos en el exterior. Es un servicio seguro vinculado a cuentas bancarias de EE.UU. Sin embargo, siempre recomendamos pagar solo después de que el posadero confirme tu reserva y confirmar sus datos de pago por el chat de RESER-VE. Nunca envíes dinero a datos recibidos fuera de la plataforma.": "Zelle is the most widely used payment method among Venezuelans abroad. It is a secure service linked to US bank accounts. Still, we always recommend paying only after the host confirms your booking and confirming their payment details in the RESER-VE chat. Never send money to details received outside the platform.",
  "Posadas y destinos": "Posadas and destinations",
  "¿Qué es una posada venezolana?": "What is a Venezuelan posada?",
  "Una posada es un alojamiento pequeño, generalmente familiar, que forma parte de la tradición turística venezolana. A diferencia de los hoteles de cadena, las posadas ofrecen una experiencia personal, auténtica y cercana. El posadero suele vivir en el lugar y conoce a fondo su región.": "A posada is a small, usually family-run guesthouse and part of Venezuela’s travel tradition. Unlike chain hotels, posadas offer a personal, authentic and warm experience. The host usually lives on site and knows the region inside out.",
  "¿Las posadas están verificadas?": "Are posadas verified?",
  "Sí. Antes de publicar cualquier posada en RESER-VE, nuestro equipo verifica la información del alojamiento, las fotos y los datos del anfitrión. Además, solo publicamos reseñas de huéspedes con una reserva confirmada en la plataforma.": "Yes. Before any posada goes live on RESER-VE, our team checks the listing details, photos and host information. And we only publish reviews from guests with a confirmed booking on the platform.",
  "¿Cuáles son los destinos disponibles?": "Which destinations are available?",
  "Actualmente cubrimos las principales regiones turísticas de Venezuela: Los Roques, Isla Margarita, Mochima, Morrocoy, Canaima, Gran Sabana, Mérida, Choroní y más. Estamos agregando nuevas posadas constantemente.": "We currently cover Venezuela's main travel regions: Los Roques, Margarita Island, Mochima, Morrocoy, Canaima, Gran Sabana, Mérida, Choroní and more. We're adding new posadas all the time.",
  "¿Puedo buscar por región?": "Can I search by region?",
  "Sí. En el buscador puedes seleccionar regiones completas como \"Caribe Central\", \"Los Andes\", \"Islas del Caribe\" o \"Gran Sabana y Canaima\", y ver todas las posadas disponibles en esa zona.": "Yes. In the search you can pick whole regions such as \"Central Caribbean\", \"The Andes\", \"Caribbean Islands\" or \"Gran Sabana & Canaima\" and see every posada available there.",
  "Para posaderos": "For hosts",
  "¿Cómo publico mi posada en RESER-VE?": "How do I list my posada on RESER-VE?",
  "Crea una cuenta como posadero, entra a tu panel y pulsa \"Publicar mi primera posada\". Sube fotos, habitaciones, precios y métodos de cobro. Nuestro equipo la revisa en 24–72 horas y te avisa por correo cuando esté publicada. Publicar es gratis.": "Create a host account, open your dashboard and tap \"Publicar mi primera posada\". Upload photos, rooms, prices and payment methods. Our team reviews it within 24–72 hours and emails you when it goes live. Listing is free.",
  "¿Cuánto cobra RESER-VE a los posaderos?": "How much does RESER-VE charge hosts?",
  "Publicar es gratis y sin mensualidad. Encontrarás las condiciones completas (comisión por reserva confirmada y paridad de precio) en la página para posaderos: reser-ve.com/posaderos.": "Listing is free with no monthly fee. You'll find the full conditions (commission per confirmed booking and price parity) on the hosts page: reser-ve.com/posaderos.",
  "¿Quién controla los precios y disponibilidad?": "Who controls prices and availability?",
  "Tú como posadero tienes control total sobre tus precios, métodos de pago aceptados y políticas de la posada. La comunicación con el huésped se hace por el chat de RESER-VE, para proteger a ambas partes.": "As the host you have full control over your prices, accepted payment methods and house policies. Communication with guests happens in the RESER-VE chat to protect both sides.",
  "Qué es RESER-VE y por qué nos enfocamos en las posadas de Venezuela.": "What RESER-VE is and why we focus on Venezuela's posadas.",
  "Registra tu posada": "List your posada",
  "Por qué": "Why",
  "posadas": "posadas",
  "Explora las": "Explore the",
  ", una comunidad de viajeros venezolanos.": ", a community of Venezuelan travelers.",
  "Posada en Canaima, Venezuela": "Posada in Canaima, Venezuela",
  "Posaderos": "For hosts",
  "Sobre nosotros": "About us",
  "En Venezuela, la mejor forma de conocer un destino suele ser quedarse en una posada. Queremos que encontrarlas y reservarlas sea igual de fácil que reservar un hotel.": "In Venezuela, the best way to get to know a place is usually to stay at a posada. We want finding and booking them to be as easy as booking a hotel.",
  "Qué es una posada": "What a posada is",
  "Pequeñas, familiares y bien ubicadas": "Small, family-run and well located",
  "Una posada es un alojamiento pequeño, normalmente de pocas habitaciones, que gestiona una familia. Los dueños suelen vivir en el lugar o muy cerca y conocen bien la zona: saben qué tour vale la pena, quién hace el mejor traslado y dónde comer.": "A posada is a small guesthouse, usually with just a few rooms, run by a family. The owners tend to live on site or close by and know the area well: which tour is worth it, who does the best transfer and where to eat.",
  "Hay posadas frente al mar en Los Roques y Mochima, en la montaña en Mérida, en pueblos coloniales como Coro o junto a los tepuyes de la Gran Sabana. En muchos de esos lugares no hay hoteles grandes: las posadas son la forma principal de alojarse.": "There are beachfront posadas in Los Roques and Mochima, mountain ones in Mérida, others in colonial towns like Coro or next to the tepuis of the Gran Sabana. In many of these places there are no big hotels: posadas are the main way to stay.",
  "El problema": "The problem",
  "Difíciles de encontrar y de reservar": "Hard to find and hard to book",
  "La mayoría de las posadas no aparecen en Booking ni en Airbnb. Se reservan por WhatsApp o Instagram, sin precios claros, sin fotos actualizadas y sin ninguna garantía para quien paga por adelantado. Para quien viaja desde el exterior es todavía más difícil.": "Most posadas aren't on Booking or Airbnb. They're booked over WhatsApp or Instagram, with no clear prices, no up-to-date photos and no guarantee for whoever pays in advance. For travelers coming from abroad it's even harder.",
  "Qué hacemos": "What we do",
  "Un solo lugar para buscar, comparar y reservar": "One place to search, compare and book",
  "En RESER-VE cada posada tiene su página con fotos, precio por noche, servicios, políticas y ubicación. Nuestro equipo revisa cada una antes de publicarla. El viajero paga exactamente el precio publicado y coordina todo con el posadero por un chat dentro de la plataforma, que deja registro de lo acordado.": "On RESER-VE every posada has its own page with photos, nightly price, amenities, policies and location. Our team reviews each one before it goes live. Travelers pay exactly the listed price and coordinate everything with the host through an in-platform chat that keeps a record of what was agreed.",
  "Los pagos se hacen como ya funciona en Venezuela: Zelle, Pago Móvil, transferencia o efectivo, según lo que acepte cada posada.": "Payments work the way they already do in Venezuela: Zelle, Pago Móvil, bank transfer or cash, depending on what each posada accepts.",
  "Busca por destino, precio o forma de pago.": "Search by destination, price or payment method.",
  "Ver posadas": "Browse posadas",
  "Tengo una posada": "I have a posada",
  "Inicio": "Home",
  "Publica tu posada gratis en RESER-VE. Solo pagas una comisión cuando recibes una reserva confirmada.": "List your posada for free on RESER-VE. You only pay a commission when you get a confirmed booking.",
  "Más viajeros": "More travelers",
  "Tu posada aparece en el buscador, el mapa y las páginas de destino, para viajeros de Venezuela y venezolanos que viven fuera.": "Your posada shows up in search, on the map and on destination pages, for travelers in Venezuela and Venezuelans living abroad.",
  "Solo pagas si ganas": "You only pay when you earn",
  "Publicar es gratis y sin mensualidad. Solo aplica un 10% sobre las reservas confirmadas, menos que el 15–18% de las grandes plataformas. El huésped nunca paga comisión extra.": "Listing is free with no monthly fee. Only 10% applies on confirmed bookings, less than the 15–18% of the big platforms. Guests never pay an extra fee.",
  "Chat seguro con el huésped": "Safe chat with guests",
  "Coordina llegada, preferencias y detalles con cada viajero desde la mensajería de RESER-VE. Todo queda registrado, lo que protege a ambas partes si hay un malentendido.": "Coordinate arrival, preferences and details with each traveler through RESER-VE messaging. Everything is recorded, which protects both sides if there is a misunderstanding.",
  "Reseñas verificadas": "Verified reviews",
  "Solo pueden opinar huéspedes que se alojaron en tu posada a través de RESER-VE.": "Only guests who stayed at your posada through RESER-VE can leave a review.",
  "Tu propia página": "Your own page",
  "Fotos, descripción, servicios, políticas, ubicación y reseñas, sin tener que crear ni mantener un sitio web.": "Photos, description, amenities, policies, location and reviews, without having to build or maintain a website.",
  "Calendario sin overbooking": "A calendar with no overbooking",
  "Anota las reservas que te llegan por WhatsApp o teléfono y sincroniza Booking, Airbnb o Google Calendar. Cada noche ves cuántas habitaciones te quedan libres.": "Log the bookings you get by WhatsApp or phone and sync Booking, Airbnb or Google Calendar. For every night you see how many rooms are still free.",
  "Regístrate": "Sign up",
  "Crea tu cuenta de posadero y publica tu posada desde tu panel: fotos, habitaciones, precios y métodos de cobro. Toma unos 10 minutos.": "Create your host account and list your posada from your dashboard: photos, rooms, prices and payment methods. It takes about 10 minutes.",
  "Revisamos tu perfil": "We review your profile",
  "Nuestro equipo verifica la información en 24–72 horas y te avisa por correo. Si falta algo, te ayudamos a completarlo.": "Our team checks the information within 24–72 hours and emails you. If anything is missing, we'll help you complete it.",
  "Publicada": "Live",
  "Tu posada aparece en el buscador, el mapa y las sugerencias. Durante la fase privada ya se ve en la web; al abrir las reservas, estarás lista desde el día uno.": "Your posada appears in search, on the map and in suggestions. During the private beta it's already visible on the site; when bookings open, you'll be ready from day one.",
  "Recibe huéspedes": "Welcome guests",
  "Te llega un correo con cada solicitud. La confirmas desde tu panel, coordinas por el chat de la app y cobras con tus métodos habituales.": "You get an email for every request. Confirm it from your dashboard, coordinate through the in-app chat and get paid with your usual methods.",
  "Publica tu posada": "List your posada",
  "en RESER-VE": "on RESER-VE",
  "Publicar mi posada": "List my posada",
  "Publicar y mantener tu posada": "Listing and keeping your posada",
  "Sin mensualidad, sin costo de alta, sin permanencia. Puedes pausar tu publicación cuando quieras (al reactivarla pasa por una revisión rápida).": "No monthly fee, no sign-up cost, no lock-in. You can pause your listing whenever you want (reactivating it goes through a quick review).",
  "Solo por reserva confirmada": "Only per confirmed booking",
  "Lo asume la posada; el viajero paga exactamente tu precio.": "Paid by the posada; the traveler pays exactly your price.",
  "Tarifa fundadora:": "Founder rate:",
  "si te unes en la fase privada, 10% garantizado 12 meses desde la apertura.": "join during the private beta and keep 10% guaranteed for 12 months from launch.",
  "Paridad de precio": "Price parity",
  "El precio en RESER-VE debe ser el mismo que en tus otros canales, y si haces una oferta o promoción en otro lado, también debe estar aquí. Incumplirlo puede llevar a la suspensión.": "Your price on RESER-VE must match your other channels, and any offer or promotion you run elsewhere must also be here. Breaching this may lead to suspension.",
  "Todo por la app": "Everything in the app",
  "La comunicación con huéspedes se hace por el chat de RESER-VE. Así evitamos fraudes y protegemos a ambas partes.": "Communication with guests happens in the RESER-VE chat. That way we prevent fraud and protect both sides.",
  "Chat": "Chat",
  "Estamos en fase privada (MVP).": "We're in private beta (MVP).",
  "Ya puedes crear tu cuenta y publicar tu posada; las reservas del público se abrirán en unas semanas, cuando terminemos de perfeccionar el proceso de pago y reserva. Las posadas fundadoras mantienen el 10% de comisión durante 12 meses tras la apertura y salen primero en el lanzamiento. Más adelante ofreceremos servicios opcionales de fotografía profesional y digitalización.": "You can already create your account and list your posada; public bookings will open in a few weeks, once we finish polishing payments and booking. Founding posadas keep the 10% commission for 12 months after launch and are featured first at launch. Later on we will offer optional professional photography and digitization services.",
  "Para posaderos · Fase privada": "For hosts · Private beta",
  "Llega a viajeros de Venezuela y del exterior que buscan dónde quedarse. Publicar es gratis: solo pagas un 10% cuando recibes una reserva confirmada.": "Reach travelers from Venezuela and abroad looking for a place to stay. Listing is free: you only pay 10% when you get a confirmed booking.",
  "Cómo funciona": "How it works",
  "Por qué RESER-VE": "Why RESER-VE",
  "Qué te ofrece RESER-VE": "What RESER-VE offers you",
  "Hecha para cómo funcionan las posadas en Venezuela.": "Built for the way posadas work in Venezuela.",
  "¿Quiénes somos?": "Who are we?",
  "Condiciones claras": "Clear conditions",
  "Reglas simples, sin letra pequeña": "Simple rules, no fine print",
  "Lee la guía completa para posaderos →": "Read the full host guide (Spanish) →",
  "Proceso": "Process",
  "Cómo empezar": "How to get started",
  "Toma unos 10 minutos.": "It takes about 10 minutes.",
  "Crea tu cuenta de posadero y envía tu posada a revisión. Si tienes dudas, escríbenos a hola@reser-ve.com.": "Create your host account and submit your posada for review. Questions? Email us at hola@reser-ve.com.",
  "Registrar mi posada": "Register my posada",
  "Descargar guía (PDF)": "Download guide (PDF, Spanish)",
  "Destino no encontrado": "Destination not found",
  "Posadas en {place}": "Posadas in {place}",
  "Descubre posadas auténticas en {place}, Venezuela: {tag}. Fotos, precios y métodos de pago en RESER-VE.": "Discover authentic posadas in {place}, Venezuela: {tag}. Photos, prices and payment methods on RESER-VE.",
  "Posadas en": "Posadas in",
  "Nuevo": "New",
  "valoración promedio": "average rating",
  "destino en RESER-VE": "destination on RESER-VE",
  "/ noche": "/ night",
  "{n} reseñas": "{n} reviews",
  "Nueva en RESER-VE": "New on RESER-VE",
  "disponibles": "available",
  "Selecciona la opción que mejor se adapte a tu viaje y descubre una forma más cálida, local y confiable de hospedarte en Venezuela.": "Pick the option that best suits your trip and discover a warmer, more local and trustworthy way to stay in Venezuela.",
  "¿Tu primera vez en {place}?": "First time in {place}?",
  "Reserva con mínimo 2 semanas de antelación. La mayoría de posadas en este destino se agotan rápido, especialmente en temporada alta.": "Book at least 2 weeks ahead. Most posadas here fill up fast, especially in high season.",
  "Destinos": "Destinations",
  "posadas disponibles": "posadas available",
  "Flexible": "Flexible",
  "USD, bolívares, Zelle, Binance y más": "USD, bolívars, Zelle, Binance and more",
  "Boutique": "Boutique",
  "estancias locales y auténticas": "local, authentic stays",
  "Alojamientos": "Stays",
  "Ver posada →": "View posada →",
  "Explorar posadas disponibles →": "Explore available posadas →",
  "Posadas auténticas de Venezuela": "Authentic posadas of Venezuela",
  "Archipiélago": "Archipelago",
  "Costa Oriental": "Eastern coast",
  "Costa Occidental": "Western coast",
  "Salto Ángel": "Angel Falls",
  "Tierra de tepuyes": "Land of tepuis",
  "Caribe": "Caribbean",
  "Costa Central": "Central coast",
  "Dunas & Colonial": "Dunes & colonial",
  "Descubre posadas auténticas en el archipiélago de Los Roques, con aguas turquesa, cayos desiertos y una experiencia cálida conectada con el mar.": "Discover authentic posadas in the Los Roques archipelago, with turquoise water, deserted cays and a warm experience close to the sea.",
  "Encuentra posadas acogedoras en Mérida, rodeadas de montaña, páramo y la hospitalidad andina más auténtica.": "Find cozy posadas in Mérida, surrounded by mountains, páramo and the most authentic Andean hospitality.",
  "Explora posadas en Mochima y la costa de Sucre para una experiencia frente al mar, entre playas vírgenes, cocoteros y tranquilidad.": "Explore posadas in Mochima and the Sucre coast for a seaside stay among untouched beaches, coconut palms and calm.",
  "Descubre posadas en Morrocoy para disfrutar de cayos increíbles, buceo y atardeceres sobre el manglar.": "Discover posadas in Morrocoy to enjoy incredible cays, diving and sunsets over the mangroves.",
  "Hospédate frente a la laguna de Canaima y el Salto Ángel, uno de los destinos más extraordinarios del planeta, con una experiencia auténtica Pemón.": "Stay by the Canaima lagoon and Angel Falls, one of the most extraordinary places on the planet, with an authentic Pemón experience.",
  "Posadas y campamentos en la Gran Sabana, entre tepuyes milenarios, ríos de jaspe y la cultura indígena Pemón.": "Posadas and camps in the Gran Sabana, among ancient tepuis, jasper rivers and the Indigenous Pemón culture.",
  "Encuentra posadas boutique en Isla Margarita para una experiencia relajada, tropical y memorable junto a Playa El Agua.": "Find boutique posadas on Margarita Island for a relaxed, tropical and memorable stay near Playa El Agua.",
  "Posadas coloniales en Choroní y Chuao, entre el Parque Nacional Henri Pittier, playas de arena dorada, tambores y el mejor cacao del mundo.": "Colonial posadas in Choroní and Chuao, between Henri Pittier National Park, golden beaches, drums and the world's finest cacao.",
  "Posadas en Santa Ana de Coro, Patrimonio de la Humanidad, a minutos de los médanos de arena dorada a orillas del Caribe.": "Posadas in Santa Ana de Coro, a World Heritage Site, minutes from the golden sand dunes on the Caribbean shore.",
  "RESER-VE es un proyecto respaldado por": "RESER-VE is a project backed by",
  "Respaldado por": "Backed by",
  "RESER-VE es un proyecto respaldado por Dos Locos de Viaje, una comunidad de viajeros venezolanos. Te contamos por qué nos enfocamos en las posadas.": "RESER-VE is a project backed by Dos Locos de Viaje, a community of Venezuelan travelers. Here is why we focus on posadas.",
  "RESER-VE es un proyecto respaldado por Dos Locos de Viaje, una comunidad venezolana de viajeros que cree en el turismo auténtico y responsable. Cada posada listada es revisada manualmente para garantizar calidad.": "RESER-VE is a project backed by Dos Locos de Viaje, a Venezuelan travel community that believes in authentic, responsible tourism. Every listed posada is reviewed by hand to guarantee quality.",
}
