export const legal: Record<string, string> = {
  "Última actualización: septiembre 2026": "Last updated: September 2026",
  "_legal_nota": "This is a translation; the Spanish version prevails.",
  "Términos y Condiciones": "Terms and Conditions",
  "Términos y condiciones de uso de RESER-VE.": "RESER-VE terms and conditions of use.",
  "¿Dudas sobre estos términos? Escríbenos a": "Questions about these terms? Email us at",
  "Consulta también nuestra": "See also our",
  "Política de Privacidad": "Privacy Policy",
  "1. Qué es RESER-VE": "1. What RESER-VE is",
  "RESER-VE es una plataforma que conecta viajeros con posadas y anfitriones locales (\"posaderos\") en Venezuela. RESER-VE facilita el descubrimiento y la solicitud de reservas, pero no es propietaria ni operadora de las posadas listadas.": "RESER-VE is a platform that connects travelers with posadas and local hosts (\"posaderos\") in Venezuela. RESER-VE makes it easy to discover posadas and request bookings, but it does not own or operate the listed posadas.",
  "La relación de alojamiento se establece directamente entre el viajero y el posadero.": "The accommodation relationship is established directly between the traveler and the host.",
  "2. Reservas y pagos": "2. Bookings and payments",
  "Al solicitar una reserva, el viajero envía una solicitud que el posadero puede confirmar o rechazar. Una reserva solo es firme cuando el posadero la confirma.": "When requesting a booking, the traveler sends a request that the host can confirm or decline. A booking is only firm once the host confirms it.",
  "El precio mostrado es el precio final que paga el viajero; RESER-VE no añade comisiones al viajero. El pago se coordina directamente con el posadero mediante el método acordado (Zelle, Pago Móvil, transferencia, efectivo, etc.).": "The price shown is the final price the traveler pays; RESER-VE adds no fees for travelers. Payment is arranged directly with the host using the agreed method (Zelle, Pago Móvil, bank transfer, cash, etc.).",
  "RESER-VE no procesa ni custodia los pagos entre viajero y posadero. Recomendamos verificar los datos del anfitrión antes de transferir.": "RESER-VE does not process or hold payments between traveler and host. We recommend verifying the host's details before transferring.",
  "3. Cancelaciones": "3. Cancellations",
  "Cada posada define su propia política de cancelación, indicada en su página. El viajero puede cancelar una solicitud en estado \"pendiente\" desde su panel de reservas.": "Each posada sets its own cancellation policy, shown on its page. Travelers can cancel a \"pending\" request from their bookings page.",
  "Las solicitudes pendientes que no sean respondidas por el posadero en 24 horas se cancelan automáticamente.": "Pending requests that the host doesn't answer within 24 hours are cancelled automatically.",
  "4. Responsabilidades del posadero": "4. Host responsibilities",
  "El posadero es responsable de la exactitud de la información publicada (fotos, precios, servicios, disponibilidad) y de la calidad del alojamiento. RESER-VE revisa las posadas antes de publicarlas, pero no garantiza cada estancia.": "The host is responsible for the accuracy of the published information (photos, prices, amenities, availability) and the quality of the accommodation. RESER-VE reviews posadas before publishing them but does not guarantee every stay.",
  "Paridad de precios: el precio publicado en RESER-VE debe ser igual o mejor que el ofrecido por el posadero en otros canales (WhatsApp, redes sociales, página propia, Booking, Airbnb u otros) para la misma posada y fechas. No se permite inflar el precio en la plataforma para trasladar la comisión al viajero.": "Price parity: the price published on RESER-VE must be equal to or better than the one the host offers on other channels (WhatsApp, social media, own website, Booking, Airbnb or others) for the same posada and dates. Inflating the price on the platform to pass the commission on to the traveler is not allowed.",
  "Ofertas y promociones: si el posadero ofrece un descuento, promoción o tarifa especial en cualquier otro canal, debe ofrecer la misma condición en RESER-VE durante el mismo periodo.": "Offers and promotions: if the host offers a discount, promotion or special rate on any other channel, they must offer the same terms on RESER-VE for the same period.",
  "Comunicación y pagos dentro de la plataforma: el posadero no debe invitar a los viajeros que lo contactaron por RESER-VE a reservar o pagar por otros canales para evitar la comisión.": "Communication and payments inside the platform: hosts must not invite travelers who contacted them through RESER-VE to book or pay through other channels to avoid the commission.",
  "Incumplimientos: RESER-VE revisa las conversaciones de la plataforma con herramientas automáticas y atiende los avisos de los viajeros. Incumplir la paridad de precios, las ofertas equivalentes o la regla de comunicación dentro de la plataforma puede dar lugar a un aviso y, si se repite, a la suspensión de la posada o de la cuenta.": "Breaches: RESER-VE reviews conversations on the platform with automated tools and follows up on travelers' reports. Breaching price parity, equivalent offers or the in-platform communication rule may lead to a warning and, if repeated, to suspension of the posada or the account.",
  "5. Conducta del usuario": "5. User conduct",
  "Los usuarios se comprometen a proporcionar información veraz, a no usar la plataforma con fines fraudulentos y a tratar con respeto a anfitriones y demás viajeros.": "Users agree to provide truthful information, not to use the platform for fraudulent purposes and to treat hosts and other travelers with respect.",
  "Para prevenir fraudes y proteger a ambas partes, los mensajes entre viajeros y posaderos pueden ser revisados de forma automatizada y, si hay una alerta, por el equipo de RESER-VE.": "To prevent fraud and protect both sides, messages between travelers and hosts may be reviewed automatically and, if there is an alert, by the RESER-VE team.",
  "RESER-VE puede suspender cuentas o posadas que incumplan estos términos.": "RESER-VE may suspend accounts or posadas that breach these terms.",
  "6. Reseñas": "6. Reviews",
  "Solo los viajeros con una reserva confirmada o completada pueden dejar reseñas. Las reseñas deben ser honestas y respetuosas.": "Only travelers with a confirmed or completed booking can leave reviews. Reviews must be honest and respectful.",
  "7. Limitación de responsabilidad": "7. Limitation of liability",
  "RESER-VE actúa como intermediario tecnológico. No se hace responsable de disputas, daños o incumplimientos derivados de la relación directa entre viajero y posadero, dentro de lo permitido por la ley.": "RESER-VE acts as a technology intermediary. To the extent permitted by law, it is not liable for disputes, damages or breaches arising from the direct relationship between traveler and host.",
  "8. Cambios": "8. Changes",
  "RESER-VE puede actualizar estos términos. El uso continuado de la plataforma implica la aceptación de la versión vigente.": "RESER-VE may update these terms. Continued use of the platform means accepting the current version.",
  "Cómo RESER-VE recopila, usa y protege tus datos.": "How RESER-VE collects, uses and protects your data.",
  "Consulta también nuestros": "See also our",
  "1. Datos que recopilamos": "1. Data we collect",
  "Recopilamos los datos que nos proporcionas al crear una cuenta (nombre, correo electrónico y contraseña cifrada), al reservar (fechas, número de huéspedes, método de pago preferido y notas) y al comunicarte con posaderos o con soporte.": "We collect the data you give us when creating an account (name, email and encrypted password), when booking (dates, number of guests, preferred payment method and notes) and when you communicate with hosts or support.",
  "Si publicas una posada, recopilamos la información del listado (fotos, descripción, ubicación, precios y datos de contacto).": "If you list a posada, we collect the listing information (photos, description, location, prices and contact details).",
  "2. Cómo usamos tus datos": "2. How we use your data",
  "Usamos tus datos para operar la plataforma: mostrar posadas, gestionar solicitudes de reserva, facilitar la comunicación entre viajero y posadero, enviar notificaciones por correo y mejorar el servicio.": "We use your data to run the platform: show posadas, manage booking requests, enable communication between traveler and host, send email notifications and improve the service.",
  "No vendemos tus datos personales a terceros.": "We do not sell your personal data to third parties.",
  "3. Asistente de IA": "3. AI assistant",
  "Nuestros asistentes de IA (Chigüi y Aurora) procesan tus mensajes para ayudarte a reservar y responder consultas. No compartimos datos sensibles de pago con ellos y sus respuestas pueden contener errores.": "Our AI assistants (Chigüi and Aurora) process your messages to help you book and answer questions. We don't share sensitive payment data with them, and their answers may contain mistakes.",
  "4. Con quién compartimos datos": "4. Who we share data with",
  "Compartimos con el posadero los datos necesarios para gestionar tu reserva (nombre, fechas, contacto). Usamos proveedores de infraestructura (alojamiento, base de datos, envío de correos) que procesan datos en nuestro nombre bajo acuerdos de confidencialidad.": "We share with the host the data needed to manage your booking (name, dates, contact). We use infrastructure providers (hosting, database, email delivery) that process data on our behalf under confidentiality agreements.",
  "5. Seguridad": "5. Security",
  "Las contraseñas se almacenan cifradas. Aplicamos medidas razonables para proteger tu información, aunque ningún sistema es 100% infalible. Nunca te pediremos tu contraseña ni datos completos de tarjeta por correo o chat.": "Passwords are stored encrypted. We apply reasonable measures to protect your information, although no system is 100% foolproof. We will never ask for your password or full card details by email or chat.",
  "6. Tus derechos": "6. Your rights",
  "Puedes acceder, corregir o eliminar tus datos personales escribiéndonos. También puedes cerrar tu cuenta en cualquier momento.": "You can access, correct or delete your personal data by writing to us. You can also close your account at any time.",
  "7. Cookies": "7. Cookies",
  "Usamos cookies estrictamente necesarias para mantener tu sesión iniciada, recordar tu idioma y el funcionamiento del sitio.": "We use strictly necessary cookies to keep you signed in, remember your language and keep the site working.",
  "8. Contacto": "8. Contact",
  "Para cualquier asunto relacionado con tu privacidad, escríbenos a hola@reser-ve.com.": "For any privacy-related matter, email us at hola@reser-ve.com.",
}
