export const meta: Record<string, string> = {
  "Nueva contraseña": "New password",
  "Crea una nueva contraseña para tu cuenta de RESER-VE.": "Create a new password for your RESER-VE account.",
  "Recuperar contraseña": "Recover password",
  "Recupera el acceso a tu cuenta de RESER-VE.": "Get back into your RESER-VE account.",
  "Mi cuenta": "My account",
  "Buscar posadas en Venezuela": "Search posadas in Venezuela",
  "Busca posadas por destino, precio y método de pago, con mapa: Los Roques, Mérida, Mochima, Morrocoy, Canaima, Margarita y más.": "Search posadas by destination, price and payment method, with a map: Los Roques, Mérida, Mochima, Morrocoy, Canaima, Margarita and more.",
  "Iniciar sesión": "Sign in",
  "Entra a tu cuenta de RESER-VE.": "Sign in to your RESER-VE account.",
  "Crear cuenta": "Create account",
  "Crea tu cuenta gratis en RESER-VE como viajero o posadero.": "Create your free RESER-VE account as a traveler or host.",
  "Sueña tu viaje con Aurora": "Dream your trip with Aurora",
  "Aurora, la guacamaya viajera de RESER-VE, te arma la ruta por Venezuela con posadas reales, fechas y precios.": "Aurora, RESER-VE's traveling macaw, builds your route through Venezuela with real posadas, dates and prices.",
  "RESER-VE | Posadas en Venezuela": "RESER-VE | Posadas in Venezuela",
  "Encuentra y reserva posadas en Los Roques, Mérida, Mochima, Canaima, la Gran Sabana y más. Sin comisiones para el viajero.": "Find and book posadas in Los Roques, Mérida, Mochima, Canaima, the Gran Sabana and more. No fees for travelers.",
  "Encuentra y reserva posadas en Los Roques, Mérida, Mochima, Canaima y más.": "Find and book posadas in Los Roques, Mérida, Mochima, Canaima and more.",
  "Encuentra y reserva posadas en Venezuela.": "Find and book posadas in Venezuela.",
  "Posadas de Venezuela": "Posadas of Venezuela",
}
