export const reserva: Record<string, string> = {
  "Inicia sesión para reservar": "Sign in to book",
  "Datos inválidos": "Invalid data",
  "Fechas inválidas": "Invalid dates",
  "La llegada no puede ser en el pasado": "Check-in can't be in the past",
  "La salida debe ser posterior a la llegada": "Check-out must be after check-in",
  "La estadía máxima es de 30 noches": "The maximum stay is 30 nights",
  "Solo se puede reservar hasta 18 meses por adelantado": "You can only book up to 18 months in advance",
  "Posada no disponible": "Posada not available",
  "Esas fechas ya no están disponibles": "Those dates are no longer available",
  "Estamos en fase privada: las posadas se están sumando y las reservas abren muy pronto.": "We're in private beta: posadas are joining and bookings open very soon.",
  "Inicia sesión para contactar al posadero": "Sign in to contact the host",
  "Posada no encontrada": "Posada not found",
  "Esta posada aún no tiene un posadero asignado": "This posada doesn't have a host assigned yet",
  "No puedes contactarte a ti mismo": "You can't message yourself",
  "Mensaje vacío": "Empty message",
  "Faltan campos requeridos": "Missing required fields",
  "USD desde EE.UU. o internacionalmente": "USD from the US or internationally",
  "Billetera digital en USD": "USD digital wallet",
  "Transferencia en bolívares": "Transfer in bolívars",
  "Error al crear la reserva": "Couldn't create the booking",
  "Error de red. Intenta de nuevo.": "Network error. Please try again.",
  "Enviando solicitud…": "Sending request…",
  "Confirmar reserva": "Confirm booking",
  "Cargando…": "Loading…",
  "← Volver a búsqueda": "← Back to search",
  "Redirigiendo…": "Redirecting…",
  "✓ Posada": "✓ Posada",
  "Reserva": "Booking",
  "Confirmación": "Confirmation",
  "← Volver": "← Back",
  "Completa tu reserva": "Complete your booking",
  "Revisa los detalles y confirma. El posadero aceptará en 24h.": "Review the details and confirm. The host will reply within 24h.",
  "Fechas de estancia": "Dates of stay",
  "Notas para el posadero (opcional)": "Notes for the host (optional)",
  "Método de pago preferido": "Preferred payment method",
  "Esas fechas no están disponibles para esta posada. Por favor elige otras.": "Those dates aren't available for this posada. Please choose others.",
  "Tu reserva queda registrada y protegida en RESER-VE": "Your booking is recorded and protected on RESER-VE",
  "Total": "Total",
  "Selecciona fechas para ver el total": "Select dates to see the total",
  "← Volver a {name}": "← Back to {name}",
  "Reservando como": "Booking as",
  "Llegada": "Check-in",
  "Salida": "Check-out",
  "Hora de llegada estimada, peticiones especiales, alergias…": "Estimated arrival time, special requests, allergies…",
  "Recibirás las instrucciones de pago cuando el posadero confirme.": "You'll get payment instructions once the host confirms.",
  "Sin cargos automáticos.": "No automatic charges.",
  "{n} noches": "{n} nights",
  "{n} noche": "{n} night",
  "{n} reseñas": "{n} reviews",
  "{n} hab.": "{n} rooms",
  " por {method}": " via {method}",
  "No pagues todavía. Cuando el posadero confirme tu reserva te llegará un correo y te enviará sus datos de pago{via} por el chat de RESER-VE (Mis mensajes). Monto: ${total} USD · referencia {code}. Nunca envíes dinero a datos recibidos fuera de la plataforma.": "Don't pay yet. When the host confirms your booking you'll get an email, and they'll send you their payment details{via} through the RESER-VE chat (Messages). Amount: ${total} USD · reference {code}. Never send money to details received outside the platform.",
  "Cargando tu reserva…": "Loading your booking…",
  "No se encontraron datos de reserva.": "No booking details found.",
  "Ver mis reservas →": "See my bookings →",
  "✓ Reserva": "✓ Booking",
  "✓ Confirmada": "✓ Confirmed",
  "¡Solicitud enviada!": "Request sent!",
  "Código de reserva": "Booking code",
  "Guarda este código — lo necesitarás para cualquier consulta": "Save this code — you'll need it for any inquiry",
  "Tu alojamiento": "Your stay",
  "Detalle del pago": "Payment details",
  "Ver mis reservas": "See my bookings",
  "Ver la posada": "View the posada",
  "Tu reserva está pendiente de confirmación por el posadero.": "Your booking is awaiting confirmation from the host.",
  "Recibirás instrucciones de pago cuando sea aceptada.": "You'll receive payment instructions once it's accepted.",
  "El posadero tiene": "The host has",
  "24 horas": "24 hours",
  "para confirmar o rechazar tu solicitud. Sin cargos hasta la confirmación.": "to confirm or decline your request. No charges until confirmation.",
  "{n} huéspedes": "{n} guests",
  "{n} huésped": "{n} guest",
  "Instrucciones": "Instructions",
}
