export const unify: Record<string, string> = {
  "Con la misma cuenta puedes viajar y también publicar tu posada.": "The same account lets you travel and list your posada too.",
  "No pudimos activar tu modo posadero. Intenta de nuevo.": "We couldn't activate host mode. Please try again.",
  "Publicar es gratis": "Listing is free",
  "Sin mensualidad, sin costo de alta, sin permanencia.": "No monthly fee, no sign-up cost, no lock-in.",
  "Solo por reserva confirmada": "Only per confirmed booking",
  "Lo asume la posada; el viajero paga exactamente tu precio. Tarifa fundadora garantizada 12 meses.": "Paid by the posada; travelers pay exactly your price. Founder rate guaranteed for 12 months.",
  "Mismo precio y ofertas": "Same prices and offers",
  "Igual que en tus otros canales; si haces una promoción fuera, también va aquí.": "Same as on your other channels; any promotion you run elsewhere goes here too.",
  "Todo por la app": "Everything in the app",
  "Hablas con los huéspedes por el chat de RESER-VE.": "You talk to guests through the RESER-VE chat.",
  "Modo posadero": "Host mode",
  "{name}, publica tu posada": "{name}, list your posada",
  "Usas la misma cuenta para viajar y para recibir huéspedes. Tus reservas como viajero siguen en": "You use the same account to travel and to host guests. Your trips stay in",
  "Acepto las": "I accept the",
  "y los": "and the",
  "Activando…": "Activating…",
  "Empezar a publicar mi posada": "Start listing my posada",
  "Ahora no": "Not now",
  "Como posadero": "As a host",
  "Como viajero": "As a traveler",
  "Reservas recibidas": "Bookings received",
  "Viajero y posadero": "Traveler & host",
  "No puedes reservar tu propia posada": "You can't book your own posada",
}
