export const viajero: Record<string, string> = {
  "No se pudo eliminar la cuenta": "Couldn't delete the account",
  "Posadero": "Host",
  "Administrador": "Administrator",
  "Viajero": "Traveler",
  "Eliminando…": "Deleting…",
  "Eliminar definitivamente": "Delete permanently",
  "Mi cuenta": "My account",
  "Cargando…": "Loading…",
  "Nombre": "Name",
  "Correo": "Email",
  "Tipo de cuenta": "Account type",
  "Miembro desde": "Member since",
  "Te enviamos un enlace": "we'll send you a link",
  "Eliminar cuenta": "Delete account",
  "Para eliminar tu cuenta primero tienes que:": "To delete your account you first need to:",
  "Mis reservas": "My bookings",
  "Reservas": "Bookings",
  "Mis posadas": "My posadas",
  "Se borrarán tus datos personales y tus favoritos, y no podrás volver a entrar. El historial de reservas y mensajes se conserva sin tu nombre ni tu correo.": "Your personal data and favorites will be deleted and you won't be able to sign in again. Booking and message history is kept without your name or email.",
  "Eliminar mi cuenta": "Delete my account",
  "Cancelar": "Cancel",
  "¿Quieres cambiar tu contraseña?": "Want to change your password?",
  "Cancelar o terminar tu reserva activa": "Cancel or finish your active booking",
  "Cancelar o terminar tus {n} reservas activas": "Cancel or finish your {n} active bookings",
  "Pausar tus posadas publicadas o en revisión:": "Pause your published or in-review posadas:",
  "Esta acción no se puede deshacer. Escribe tu contraseña y la palabra": "This cannot be undone. Type your password and the word",
  "para confirmar.": "to confirm.",
  "Tu contraseña": "Your password",
  "Escribe ELIMINAR": "Type ELIMINAR",
  "Mis favoritos": "My favorites",
  "Las posadas que has guardado para tu próxima escapada.": "The posadas you've saved for your next getaway.",
  "Explorar posadas →": "Explore posadas →",
  "Quitar": "Remove",
  "Aún no has guardado posadas.": "You haven't saved any posadas yet.",
  "Pendiente de confirmación": "Awaiting confirmation",
  "Confirmada": "Confirmed",
  "Cancelada": "Cancelled",
  "Completada": "Completed",
  "¿Cancelar esta reserva?": "Cancel this booking?",
  "No se pudo enviar la reseña": "Couldn't submit the review",
  "Error de red. Intenta de nuevo.": "Network error. Please try again.",
  "Enviando…": "Sending…",
  "Publicar reseña": "Post review",
  "Cancelando…": "Cancelling…",
  "Cancelar solicitud": "Cancel request",
  "Inicia sesión para reseñar": "Sign in to leave a review",
  "Datos inválidos": "Invalid data",
  "Solo puedes reseñar posadas donde te hospedaste": "You can only review posadas where you stayed",
  "Ya dejaste una reseña para esta posada": "You've already reviewed this posada",
  "Historial de tus estadías en posadas venezolanas": "Your stays at Venezuelan posadas",
  "Cargando tus reservas…": "Loading your bookings…",
  "Inicia sesión para ver tus reservas": "Sign in to see your bookings",
  "Iniciar sesión": "Sign in",
  "Aún no tienes reservas": "You don't have any bookings yet",
  "Las reservas abren muy pronto. Mientras tanto, explora posadas y guarda tus favoritas": "Bookings open very soon. Meanwhile, explore posadas and save your favorites",
  "Explorar posadas": "Explore posadas",
  "Ver mis favoritas →": "See my favorites →",
  "Historial": "History",
  "¡Gracias por tu reseña! ⭐": "Thanks for your review! ⭐",
  "⭐ Dejar una reseña": "⭐ Leave a review",
  "Instrucciones de pago:": "Payment instructions:",
  "Mensaje del posadero:": "Message from the host:",
  "Ver posada →": "View posada →",
  "Mensaje al posadero →": "Message the host →",
  "Reservas activas ({n})": "Active bookings ({n})",
  "{n} estrellas": "{n} stars",
  "¿Cómo fue tu experiencia?": "How was your experience?",
  "El posadero te enviará sus datos de pago{method} por el chat de RESER-VE. Monto: ${total} USD · referencia {code}. Paga solo a datos recibidos dentro de la app.": "The host will send you their payment details{method} through the RESER-VE chat. Amount: ${total} USD · reference {code}. Only pay to details received inside the app.",
  "{n} noches": "{n} nights",
  "{n} noche": "{n} night",
  "{n} huéspedes": "{n} guests",
  "{n} huésped": "{n} guest",
  "Todos": "All",
  "Servicio al cliente": "Customer service",
  "Todos los mensajes de la plataforma": "All messages on the platform",
  "Tus conversaciones con viajeros, posaderos y el equipo RESER-VE": "Your conversations with travelers, hosts and the RESER-VE team",
  "Enviar mensaje": "Send message",
  "No tienes conversaciones aún.": "You don't have any conversations yet.",
  "No hay conversaciones de reserva.": "No booking conversations.",
  "No hay tickets de soporte.": "No support tickets.",
  "Reserva": "Booking",
  "Soporte": "Support",
  "Con equipo RESER-VE": "With the RESER-VE team",
  "De: {name}": "From: {name}",
  "Mensajes": "Messages",
  "Contactar al equipo RESER-VE": "Contact the RESER-VE team",
  "Nuevo mensaje — Servicio al cliente": "New message — Customer service",
  "Asunto": "Subject",
  "Mensaje": "Message",
  "Cargando mensajes…": "Loading messages…",
  "¿En qué podemos ayudarte?": "How can we help you?",
  "Cuéntanos tu consulta o problema…": "Tell us your question or problem…",
  "Conversación no encontrada.": "Conversation not found.",
  "Bandeja de mensajes": "Inbox",
  "No hay mensajes aún. Sé el primero en escribir.": "No messages yet. Be the first to write.",
  "Equipo RESER-VE": "RESER-VE team",
  "Enviar": "Send",
  "Relacionado con: {name}": "Related to: {name}",
  "Escribe tu mensaje…": "Write your message…",
}
