export type VELocation = {
  id: string
  nombre: string
  lat: number
  lng: number
  region: string
  aliases: string[]
}

export const venezuelaLocations: VELocation[] = [
  {
    id: 'los-roques',
    nombre: 'Los Roques',
    lat: 11.85,
    lng: -66.75,
    region: 'Dependencias Federales',
    aliases: ['roques', 'archipielago los roques', 'gran roque', 'gran_roque', 'francisqui'],
  },
  {
    id: 'merida',
    nombre: 'Mérida',
    lat: 8.60,
    lng: -71.14,
    region: 'Andes',
    aliases: ['merida', 'los andes', 'andes', 'sierra nevada', 'mucuchies', 'mucuruba', 'tabay'],
  },
  {
    id: 'mochima',
    nombre: 'Mochima',
    lat: 10.37,
    lng: -64.34,
    region: 'Sucre / Anzoátegui',
    aliases: ['mochima', 'parque nacional mochima', 'santa fe', 'playa colorada', 'lecheria'],
  },
  {
    id: 'morrocoy',
    nombre: 'Morrocoy',
    lat: 10.87,
    lng: -68.20,
    region: 'Falcón',
    aliases: ['morrocoy', 'parque nacional morrocoy', 'tucacas', 'chichiriviche', 'cayo sombrero', 'cayo peraza'],
  },
  {
    id: 'canaima',
    nombre: 'Canaima',
    lat: 6.23,
    lng: -62.85,
    region: 'Bolívar',
    aliases: ['canaima', 'parque nacional canaima', 'salto angel', 'angel falls', 'auyantepui', 'auyán tepui'],
  },
  {
    id: 'isla-margarita',
    nombre: 'Isla Margarita',
    lat: 11.05,
    lng: -63.88,
    region: 'Nueva Esparta',
    aliases: ['margarita', 'isla margarita', 'porlamar', 'pampatar', 'playa el agua', 'nueva esparta', 'el yaque'],
  },
  {
    id: 'caracas',
    nombre: 'Caracas',
    lat: 10.49,
    lng: -66.88,
    region: 'Capital',
    aliases: ['caracas', 'distrito capital', 'dtto capital', 'el hatillo', 'chacao', 'altamira', 'las mercedes'],
  },
  {
    id: 'la-guaira',
    nombre: 'La Guaira',
    lat: 10.60,
    lng: -66.93,
    region: 'La Guaira',
    aliases: ['la guaira', 'vargas', 'maiquetia', 'caraballeda', 'naiguata', 'macuto', 'catia la mar'],
  },
  {
    id: 'choroni',
    nombre: 'Choroní',
    lat: 10.50,
    lng: -67.60,
    region: 'Aragua',
    aliases: ['choroni', 'puerto colombia', 'cuyagua', 'cata', 'henri pittier', 'maracay playa'],
  },
  {
    id: 'maracay',
    nombre: 'Maracay',
    lat: 10.24,
    lng: -67.59,
    region: 'Aragua',
    aliases: ['maracay', 'aragua', 'villa de cura', 'turmero', 'las delicias'],
  },
  {
    id: 'valencia',
    nombre: 'Valencia',
    lat: 10.16,
    lng: -68.00,
    region: 'Carabobo',
    aliases: ['valencia', 'carabobo', 'naguanagua', 'puerto cabello', 'san diego'],
  },
  {
    id: 'puerto-cabello',
    nombre: 'Puerto Cabello',
    lat: 10.47,
    lng: -68.01,
    region: 'Carabobo',
    aliases: ['puerto cabello', 'pabellón', 'patanemo', 'quizandal'],
  },
  {
    id: 'maracaibo',
    nombre: 'Maracaibo',
    lat: 10.63,
    lng: -71.64,
    region: 'Zulia',
    aliases: ['maracaibo', 'zulia', 'lago maracaibo', 'cabimas', 'ciudad ojeda'],
  },
  {
    id: 'barquisimeto',
    nombre: 'Barquisimeto',
    lat: 10.07,
    lng: -69.32,
    region: 'Lara',
    aliases: ['barquisimeto', 'lara', 'carora', 'quibor'],
  },
  {
    id: 'cumana',
    nombre: 'Cumaná',
    lat: 10.46,
    lng: -64.17,
    region: 'Sucre',
    aliases: ['cumana', 'sucre', 'araya', 'rio caribe', 'paria', 'peninsula de paria'],
  },
  {
    id: 'ciudad-bolivar',
    nombre: 'Ciudad Bolívar',
    lat: 8.12,
    lng: -63.55,
    region: 'Bolívar',
    aliases: ['ciudad bolivar', 'bolivar', 'angostura', 'caroní'],
  },
  {
    id: 'gran-sabana',
    nombre: 'Gran Sabana',
    lat: 5.65,
    lng: -61.13,
    region: 'Bolívar',
    aliases: ['gran sabana', 'santa elena', 'santa elena de uairen', 'roraima', 'tepuy', 'tepuyes', 'kavak'],
  },
  {
    id: 'san-cristobal',
    nombre: 'San Cristóbal',
    lat: 7.77,
    lng: -72.22,
    region: 'Táchira',
    aliases: ['san cristobal', 'tachira', 'la grita', 'san antonio del tachira'],
  },
  {
    id: 'punto-fijo',
    nombre: 'Punto Fijo',
    lat: 11.71,
    lng: -70.22,
    region: 'Falcón',
    aliases: ['punto fijo', 'falcon', 'paraguaná', 'paraguana', 'coro', 'medanos de coro', 'adicora'],
  },
  {
    id: 'chichiriviche',
    nombre: 'Chichiriviche',
    lat: 10.93,
    lng: -68.27,
    region: 'Falcón',
    aliases: ['chichiriviche', 'cayo sombrero', 'cayo peraza', 'flamencos'],
  },
  {
    id: 'higuerote',
    nombre: 'Higuerote',
    lat: 10.49,
    lng: -66.10,
    region: 'Miranda',
    aliases: ['higuerote', 'miranda', 'barlovento', 'playas del litoral', 'los caracas', 'carenero'],
  },
  {
    id: 'puerto-la-cruz',
    nombre: 'Puerto La Cruz',
    lat: 10.21,
    lng: -64.67,
    region: 'Anzoátegui',
    aliases: ['puerto la cruz', 'anzoategui', 'barcelona', 'lecherías', 'el morro', 'pozuelos'],
  },
  {
    id: 'puerto-ayacucho',
    nombre: 'Puerto Ayacucho',
    lat: 5.66,
    lng: -67.63,
    region: 'Amazonas',
    aliases: ['puerto ayacucho', 'amazonas', 'autana', 'cerro autana', 'tobogan de la selva'],
  },
]
